using Microsoft.EntityFrameworkCore.Infrastructure;using Microsoft.EntityFrameworkCore.Migrations;using TORSEPAN.Infrastructure.Persistence;
#nullable disable
namespace TORSEPAN.Infrastructure.Migrations;
[DbContext(typeof(TORSEPANDbContext)),Migration("20260829010000_AddAccounting")]
public partial class AddAccounting:Migration
{
 protected override void Up(MigrationBuilder m){m.CreateTable(name:"AccountingParties",columns:t=>new{Id=t.Column<Guid>("uuid",nullable:false),Name=t.Column<string>("character varying(200)",maxLength:200,nullable:false),Company=t.Column<string>("character varying(200)",maxLength:200,nullable:true),Phone=t.Column<string>("character varying(50)",maxLength:50,nullable:true),Notes=t.Column<string>("character varying(1000)",maxLength:1000,nullable:true),IsActive=t.Column<bool>("boolean",nullable:false),CreatedAt=t.Column<DateTime>("timestamp with time zone",nullable:false)},constraints:c=>c.PrimaryKey("PK_AccountingParties",x=>x.Id));m.CreateIndex("IX_AccountingParties_Name","AccountingParties","Name");m.CreateTable(name:"AccountingDocuments",columns:t=>new{Id=t.Column<Guid>("uuid",nullable:false),Type=t.Column<int>("integer",nullable:false),Title=t.Column<string>("character varying(250)",maxLength:250,nullable:false),TotalAmount=t.Column<decimal>("numeric(18,2)",nullable:false),PaidAmount=t.Column<decimal>("numeric(18,2)",nullable:false),PartyId=t.Column<Guid>("uuid",nullable:true),HandpanId=t.Column<Guid>("uuid",nullable:true),DueDate=t.Column<DateTime>("timestamp with time zone",nullable:true),Notes=t.Column<string>("character varying(1500)",maxLength:1500,nullable:true),CreatedByUserId=t.Column<Guid>("uuid",nullable:false),CreatedAt=t.Column<DateTime>("timestamp with time zone",nullable:false),SettledAt=t.Column<DateTime>("timestamp with time zone",nullable:true)},constraints:c=>{c.PrimaryKey("PK_AccountingDocuments",x=>x.Id);c.ForeignKey("FK_AccountingDocuments_AccountingParties_PartyId",x=>x.PartyId,"AccountingParties","Id",onDelete:ReferentialAction.Restrict);c.ForeignKey("FK_AccountingDocuments_Handpans_HandpanId",x=>x.HandpanId,"Handpans","Id",onDelete:ReferentialAction.Restrict);c.ForeignKey("FK_AccountingDocuments_Users_CreatedByUserId",x=>x.CreatedByUserId,"Users","Id",onDelete:ReferentialAction.Restrict);});m.CreateIndex("IX_AccountingDocuments_CreatedByUserId","AccountingDocuments","CreatedByUserId");m.CreateIndex("IX_AccountingDocuments_DueDate","AccountingDocuments","DueDate");m.CreateIndex("IX_AccountingDocuments_HandpanId","AccountingDocuments","HandpanId");m.CreateIndex("IX_AccountingDocuments_PartyId","AccountingDocuments","PartyId");m.CreateIndex("IX_AccountingDocuments_Type_CreatedAt","AccountingDocuments",new[]{"Type","CreatedAt"});}
 protected override void Down(MigrationBuilder m){m.DropTable("AccountingDocuments");m.DropTable("AccountingParties");}
}
