// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TORSEPAN.Infrastructure.Persistence;

#nullable disable

namespace TORSEPAN.Infrastructure.Migrations
{
    [DbContext(typeof(TORSEPANDbContext))]
    partial class TORSEPANDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Bowl", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BowlType")
                        .HasColumnType("integer");

                    b.Property<bool>("HasNotes")
                        .HasColumnType("boolean");

                    b.Property<int>("InstrumentType")
                        .HasColumnType("integer");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductionCode")
                        .IsUnique();

                    b.ToTable("Bowls", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Handpan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssemblyId")
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerName").HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("SaleDestination").HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<decimal?>("SalePrice").HasPrecision(18, 2).HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("SoldAt").HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SoldByUserId").HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ScaleId")
                        .HasColumnType("uuid");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssemblyId")
                        .IsUnique();

                    b.HasIndex("ScaleId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Handpans", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.HandpanAssembly", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssemblyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BottomBowlId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopBowlId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BottomBowlId")
                        .IsUnique();

                    b.HasIndex("TopBowlId")
                        .IsUnique();

                    b.ToTable("HandpanAssemblies", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BottomBowlQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("BottomBowlLowStockThreshold").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0);

                    b.Property<int>("LowStockThreshold").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0);

                    b.Property<int>("TopBowlLowStockThreshold").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0);

                    b.Property<int>("Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Usage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(7);

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TopBowlQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TopBowlCodeTemplate").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasDefaultValue("");
                    b.Property<string>("BottomBowlCodeTemplate").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)").HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.ProductionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AssemblyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BowlId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<byte?>("Duration")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HandpanId")
                        .HasColumnType("uuid");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssemblyId");

                    b.HasIndex("BowlId");

                    b.HasIndex("HandpanId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductionEvents", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Scale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Scales", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Bowl", b =>
                {
                    b.HasOne("TORSEPAN.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Handpan", b =>
                {
                    b.HasOne("TORSEPAN.Domain.Entities.HandpanAssembly", "Assembly")
                        .WithOne("Handpan")
                        .HasForeignKey("TORSEPAN.Domain.Entities.Handpan", "AssemblyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TORSEPAN.Domain.Entities.Scale", "Scale")
                        .WithMany("Handpans")
                        .HasForeignKey("ScaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assembly");

                    b.Navigation("Scale");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.HandpanAssembly", b =>
                {
                    b.HasOne("TORSEPAN.Domain.Entities.Bowl", "BottomBowl")
                        .WithMany("BottomAssemblies")
                        .HasForeignKey("BottomBowlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TORSEPAN.Domain.Entities.Bowl", "TopBowl")
                        .WithMany("TopAssemblies")
                        .HasForeignKey("TopBowlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BottomBowl");

                    b.Navigation("TopBowl");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.ProductionEvent", b =>
                {
                    b.HasOne("TORSEPAN.Domain.Entities.HandpanAssembly", "Assembly")
                        .WithMany("ProductionEvents")
                        .HasForeignKey("AssemblyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TORSEPAN.Domain.Entities.Bowl", "Bowl")
                        .WithMany("ProductionEvents")
                        .HasForeignKey("BowlId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TORSEPAN.Domain.Entities.Handpan", "Handpan")
                        .WithMany("ProductionEvents")
                        .HasForeignKey("HandpanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TORSEPAN.Domain.Entities.User", "User")
                        .WithMany("ProductionEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assembly");

                    b.Navigation("Bowl");

                    b.Navigation("Handpan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("TORSEPAN.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("TORSEPAN.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TORSEPAN.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Bowl", b =>
                {
                    b.Navigation("BottomAssemblies");

                    b.Navigation("ProductionEvents");

                    b.Navigation("TopAssemblies");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Handpan", b =>
                {
                    b.Navigation("ProductionEvents");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.HandpanAssembly", b =>
                {
                    b.Navigation("Handpan")
                        .IsRequired();

                    b.Navigation("ProductionEvents");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Scale", b =>
                {
                    b.Navigation("Handpans");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.User", b =>
                {
                    b.Navigation("ProductionEvents");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
