// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TORSEPAN.Infrastructure.Persistence;

#nullable disable

namespace TORSEPAN.Infrastructure.Migrations
{
    [DbContext(typeof(TORSEPANDbContext))]
    partial class TORSEPANDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TORSEPAN.Domain.Entities.WorkshopMessage", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<Guid>("SenderId").HasColumnType("uuid");
                b.Property<string>("Title").IsRequired().HasMaxLength(150).HasColumnType("character varying(150)");
                b.Property<string>("Body").IsRequired().HasMaxLength(4000).HasColumnType("character varying(4000)");
                b.Property<bool>("Broadcast").HasColumnType("boolean");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id"); b.HasIndex("SenderId"); b.HasIndex("CreatedAt"); b.ToTable("WorkshopMessages");
            });
            modelBuilder.Entity("TORSEPAN.Domain.Entities.WorkshopMessageReceipt", b =>
            {
                b.Property<Guid>("MessageId").HasColumnType("uuid");
                b.Property<Guid>("RecipientId").HasColumnType("uuid");
                b.Property<DateTime?>("ReadAt").HasColumnType("timestamp with time zone");
                b.HasKey("MessageId","RecipientId"); b.HasIndex("RecipientId","ReadAt"); b.ToTable("WorkshopMessageReceipts");
            });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Bowl", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("BowlType")
                        .HasColumnType("integer");

                    b.Property<bool>("HasNotes")
                        .HasColumnType("boolean");

                    b.Property<int>("InstrumentType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCustomScale")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ScaleId")
                        .HasColumnType("uuid");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductionCode")
                        .IsUnique();

                    b.HasIndex("ScaleId");

                    b.ToTable("Bowls", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.DesignType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DesignTypes", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Handpan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssemblyId")
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SaleDestination")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("ScaleId")
                        .HasColumnType("uuid");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("SoldAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SoldByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssemblyId")
                        .IsUnique();

                    b.HasIndex("ScaleId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Handpans", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.HandpanAssembly", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssemblyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BottomBowlId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TopBowlId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BottomBowlId")
                        .IsUnique();

                    b.HasIndex("TopBowlId")
                        .IsUnique();

                    b.ToTable("HandpanAssemblies", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.MarketingActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MarketingLeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NextAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegisteredBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SentText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MarketingLeadId");

                    b.ToTable("MarketingActivities");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.MarketingLead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CooperationScore")
                        .HasColumnType("numeric");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentProducts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<decimal>("SamplePurchaseScore")
                        .HasColumnType("numeric");

                    b.Property<string>("SocialContact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MarketingLeads");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BottomBowlCodeTemplate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<int>("BottomBowlLowStockThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("BottomBowlQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<int>("LowStockThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TopBowlCodeTemplate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<int>("TopBowlLowStockThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TopBowlQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.PayrollPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HandpanCodesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HandpanIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaidBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("To")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PaidAt");

                    b.ToTable("PayrollPayments", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.PayrollRate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("BowlType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsExport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsCustom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScaleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ScaleId");

                    b.ToTable("PayrollRates", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.ProductionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AssemblyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BowlId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<byte?>("Duration")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HandpanId")
                        .HasColumnType("uuid");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssemblyId");

                    b.HasIndex("BowlId");

                    b.HasIndex("HandpanId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductionEvents", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Scale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Usage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Scales", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Bowl", b =>
                {
                    b.HasOne("TORSEPAN.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TORSEPAN.Domain.Entities.Scale", "Scale")
                        .WithMany()
                        .HasForeignKey("ScaleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Material");

                    b.Navigation("Scale");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Handpan", b =>
                {
                    b.HasOne("TORSEPAN.Domain.Entities.HandpanAssembly", "Assembly")
                        .WithOne("Handpan")
                        .HasForeignKey("TORSEPAN.Domain.Entities.Handpan", "AssemblyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TORSEPAN.Domain.Entities.Scale", "Scale")
                        .WithMany("Handpans")
                        .HasForeignKey("ScaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assembly");

                    b.Navigation("Scale");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.HandpanAssembly", b =>
                {
                    b.HasOne("TORSEPAN.Domain.Entities.Bowl", "BottomBowl")
                        .WithMany("BottomAssemblies")
                        .HasForeignKey("BottomBowlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TORSEPAN.Domain.Entities.Bowl", "TopBowl")
                        .WithMany("TopAssemblies")
                        .HasForeignKey("TopBowlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BottomBowl");

                    b.Navigation("TopBowl");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.MarketingActivity", b =>
                {
                    b.HasOne("TORSEPAN.Domain.Entities.MarketingLead", "MarketingLead")
                        .WithMany("Activities")
                        .HasForeignKey("MarketingLeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketingLead");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.PayrollRate", b =>
                {
                    b.HasOne("TORSEPAN.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TORSEPAN.Domain.Entities.Scale", "Scale")
                        .WithMany()
                        .HasForeignKey("ScaleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Material");

                    b.Navigation("Scale");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.ProductionEvent", b =>
                {
                    b.HasOne("TORSEPAN.Domain.Entities.HandpanAssembly", "Assembly")
                        .WithMany("ProductionEvents")
                        .HasForeignKey("AssemblyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TORSEPAN.Domain.Entities.Bowl", "Bowl")
                        .WithMany("ProductionEvents")
                        .HasForeignKey("BowlId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TORSEPAN.Domain.Entities.Handpan", "Handpan")
                        .WithMany("ProductionEvents")
                        .HasForeignKey("HandpanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TORSEPAN.Domain.Entities.User", "User")
                        .WithMany("ProductionEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assembly");

                    b.Navigation("Bowl");

                    b.Navigation("Handpan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("TORSEPAN.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("TORSEPAN.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TORSEPAN.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Bowl", b =>
                {
                    b.Navigation("BottomAssemblies");

                    b.Navigation("ProductionEvents");

                    b.Navigation("TopAssemblies");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Handpan", b =>
                {
                    b.Navigation("ProductionEvents");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.HandpanAssembly", b =>
                {
                    b.Navigation("Handpan")
                        .IsRequired();

                    b.Navigation("ProductionEvents");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.MarketingLead", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.Scale", b =>
                {
                    b.Navigation("Handpans");
                });

            modelBuilder.Entity("TORSEPAN.Domain.Entities.User", b =>
                {
                    b.Navigation("ProductionEvents");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
            modelBuilder.Entity("TORSEPAN.Domain.Entities.ProductionEvent", b => b.HasIndex("UserId","EventDate"));
            modelBuilder.Entity("TORSEPAN.Domain.Entities.WorkshopMessage", b =>
            {
                b.HasOne("TORSEPAN.Domain.Entities.User","Sender").WithMany().HasForeignKey("SenderId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Sender");
            });
            modelBuilder.Entity("TORSEPAN.Domain.Entities.WorkshopMessageReceipt", b =>
            {
                b.HasOne("TORSEPAN.Domain.Entities.WorkshopMessage","Message").WithMany().HasForeignKey("MessageId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("TORSEPAN.Domain.Entities.User","Recipient").WithMany().HasForeignKey("RecipientId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Message"); b.Navigation("Recipient");
            });
        }
    }
}
