namespace TORSEPAN.Panel.Models;

public sealed class ProductionAnalyticsDto { public DateTime From{get;set;} public DateTime To{get;set;} public int TopBowlCount{get;set;} public int BottomNoteBowlCount{get;set;} public int TotalBowlCount{get;set;} public int DomesticBowlCount{get;set;} public int ExportBowlCount{get;set;} public int CurrentMonthCount{get;set;} public double MonthlyAverage{get;set;} public double DifferenceFromAverage{get;set;} public List<ReportTrendDto> Trend{get;set;}=[]; public List<ReportTrendDto> DomesticBowlTrend{get;set;}=[]; public List<ReportTrendDto> ExportBowlTrend{get;set;}=[]; public int TotalHandpanCount{get;set;} public int CurrentMonthHandpanCount{get;set;} public double HandpanMonthlyAverage{get;set;} public double HandpanDifferenceFromAverage{get;set;} public List<ReportTrendDto> HandpanTrend{get;set;}=[]; public List<ReportDonutDto> Donuts{get;set;}=[]; public List<ProductionSummaryDto> Summary{get;set;}=[]; }
public sealed class ReportDonutDto { public string Title{get;set;}=""; public string Subtitle{get;set;}=""; public double Total{get;set;} public List<ReportDonutSegmentDto> Segments{get;set;}=[]; }
public sealed class ReportDonutSegmentDto { public string Label{get;set;}=""; public double Value{get;set;} public double Percentage{get;set;} public string Color{get;set;}="#173f63"; }
public sealed class ProductionSummaryDto { public string Material{get;set;}=""; public string Scale{get;set;}=""; public string Destination{get;set;}=""; public int Count{get;set;} }
public sealed class InventoryReportDto { public string Kind{get;set;}="instruments"; public DateTime From{get;set;} public DateTime To{get;set;} public int DomesticCount{get;set;} public int ExportCount{get;set;} public List<InstrumentInventoryDto> Instruments{get;set;}=[]; public List<MaterialStockReportDto> Stock{get;set;}=[]; public List<MaterialMovementDto> Movements{get;set;}=[]; public List<MaterialOutflowDto> Outflow{get;set;}=[]; }
public sealed class InstrumentInventoryDto { public Guid Id{get;set;} public string Code{get;set;}=""; public string ItemType{get;set;}=""; public string Destination{get;set;}=""; public string Material{get;set;}=""; public string Scale{get;set;}=""; public DateTime EnteredAt{get;set;} }
public sealed class MaterialStockReportDto { public Guid Id{get;set;} public string Name{get;set;}=""; public string Category{get;set;}=""; public int Quantity{get;set;} public int TopQuantity{get;set;} public int BottomQuantity{get;set;} }
public sealed class MaterialMovementDto { public string MaterialName{get;set;}=""; public string StockKind{get;set;}=""; public int Delta{get;set;} public string Direction{get;set;}=""; public string PerformedBy{get;set;}=""; public DateTime OccurredAt{get;set;} public string Reason{get;set;}=""; }
public sealed class MaterialOutflowDto { public string MaterialName{get;set;}=""; public string StockKind{get;set;}=""; public int Quantity{get;set;} }
public sealed record ManagementReportRequestDto(DateTime? From,DateTime? To,List<Guid> MaterialIds,List<Guid> ScaleIds,string Payroll,string Destination,string InventoryKind,Guid? UserId=null,int? Action=null);
