using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.EntityFrameworkCore;using TORSEPAN.Domain.Entities;using TORSEPAN.Infrastructure.Persistence;
namespace TORSEPAN.API.Controllers;
[ApiController,Route("api/accounting"),Authorize(Roles="Administrator,ProductionManager")]
public sealed class AccountingController(TORSEPANDbContext db):ControllerBase
{
 [HttpGet("summary")]public async Task<IActionResult> Summary(CancellationToken ct){var d=await db.AccountingDocuments.AsNoTracking().ToListAsync(ct);return Ok(new{CashIn=d.Where(x=>x.Type==AccountingDocumentType.Revenue).Sum(x=>x.PaidAmount),CashOut=d.Where(x=>x.Type==AccountingDocumentType.Expense).Sum(x=>x.PaidAmount),Receivables=d.Where(x=>x.Type==AccountingDocumentType.Revenue).Sum(x=>x.TotalAmount-x.PaidAmount),Payables=d.Where(x=>x.Type==AccountingDocumentType.Expense).Sum(x=>x.TotalAmount-x.PaidAmount),Overdue=d.Count(x=>x.DueDate<DateTime.UtcNow&&x.PaidAmount<x.TotalAmount)});}
 [HttpGet("parties")]public async Task<IActionResult> Parties(CancellationToken ct)=>Ok(await db.AccountingParties.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.Name).Select(x=>new{x.Id,x.Name,x.Company,x.Phone,x.Notes,Balance=db.AccountingDocuments.Where(d=>d.PartyId==x.Id).Sum(d=>d.Type==AccountingDocumentType.Revenue?d.TotalAmount-d.PaidAmount:-(d.TotalAmount-d.PaidAmount))}).ToListAsync(ct));
 [HttpPost("parties")]public async Task<IActionResult> AddParty(PartyRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name))return BadRequest("نام الزامی است.");var p=new AccountingParty(r.Name,r.Company,r.Phone,r.Notes);db.Add(p);await db.SaveChangesAsync(ct);return Ok(new{p.Id,p.Name,p.Company,p.Phone,p.Notes,Balance=0});}
 [HttpPut("parties/{id:guid}")]public async Task<IActionResult> UpdateParty(Guid id,PartyRequest r,CancellationToken ct){var p=await db.AccountingParties.FindAsync([id],ct);if(p is null)return NotFound();p.Update(r.Name,r.Company,r.Phone,r.Notes);await db.SaveChangesAsync(ct);return NoContent();}
 [HttpDelete("parties/{id:guid}")]public async Task<IActionResult> DeleteParty(Guid id,CancellationToken ct){var p=await db.AccountingParties.FindAsync([id],ct);if(p is null)return NotFound();p.Deactivate();await db.SaveChangesAsync(ct);return NoContent();}
 [HttpGet("documents")]public async Task<IActionResult> Documents([FromQuery]Guid? partyId,CancellationToken ct)=>Ok(await db.AccountingDocuments.AsNoTracking().Where(x=>!partyId.HasValue||x.PartyId==partyId).OrderByDescending(x=>x.CreatedAt).Select(x=>new{x.Id,Type=(int)x.Type,x.Title,x.TotalAmount,x.PaidAmount,Balance=x.TotalAmount-x.PaidAmount,x.DueDate,x.Notes,x.CreatedAt,x.PartyId,PartyName=x.Party!=null?x.Party.Name:"",HandpanCode=x.Handpan!=null?x.Handpan.SerialNumber:""}).ToListAsync(ct));
 [HttpPost("documents")]public async Task<IActionResult> AddDocument(DocumentRequest r,CancellationToken ct){if(!Enum.IsDefined(typeof(AccountingDocumentType),r.Type))return BadRequest();if(r.PartyId.HasValue&&!await db.AccountingParties.AnyAsync(x=>x.Id==r.PartyId&&x.IsActive,ct))return BadRequest("شخص معتبر نیست.");var d=new AccountingDocument((AccountingDocumentType)r.Type,r.Title,r.TotalAmount,r.PaidAmount,r.PartyId,null,r.DueDate,r.Notes,UserId());db.Add(d);await db.SaveChangesAsync(ct);return Ok(new{d.Id});}
 [HttpPost("documents/{id:guid}/payments")]public async Task<IActionResult> AddPayment(Guid id,PaymentRequest r,CancellationToken ct){var d=await db.AccountingDocuments.FindAsync([id],ct);if(d is null)return NotFound();try{d.AddPayment(r.Amount);await db.SaveChangesAsync(ct);return NoContent();}catch(ArgumentOutOfRangeException){return BadRequest("مبلغ پرداخت از مانده بیشتر است.");}}
 private Guid UserId()=>Guid.Parse(User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)!.Value);
}
public sealed record PartyRequest(string Name,string? Company,string? Phone,string? Notes);
public sealed record DocumentRequest(int Type,string Title,decimal TotalAmount,decimal PaidAmount,Guid? PartyId,DateTime? DueDate,string? Notes);
public sealed record PaymentRequest(decimal Amount);
