using Microsoft.EntityFrameworkCore;
using TORSEPAN.Infrastructure.Persistence;

namespace TORSEPAN.API.Services;

internal static class InstrumentNotes
{
    // NOTE: is a user-entered note. Other production descriptions are generated by the workflow.
    public static async Task<Dictionary<Guid, List<string>>> ForBowlsAsync(
        TORSEPANDbContext db, IEnumerable<Guid> bowlIds, CancellationToken ct)
    {
        var ids = bowlIds.Distinct().ToArray();
        if (ids.Length == 0) return [];
        var rows = await db.ProductionEvents.AsNoTracking()
            .Where(x => x.BowlId.HasValue && ids.Contains(x.BowlId.Value) && x.Description.StartsWith("NOTE:"))
            .OrderByDescending(x => x.EventDate)
            .Select(x => new { BowlId = x.BowlId!.Value, x.Description })
            .ToListAsync(ct);
        return rows.GroupBy(x => x.BowlId).ToDictionary(x => x.Key,
            x => x.Select(row => Text(row.Description)).Where(note => note.Length > 0).Distinct().ToList());
    }

    public static List<string> Combine(Dictionary<Guid, List<string>> notes, params Guid[] bowlIds) =>
        bowlIds.Where(notes.ContainsKey).SelectMany(id => notes[id]).Distinct().ToList();

    private static string Text(string description)
    {
        if (!description.StartsWith("NOTE:INSTRUMENT:", StringComparison.Ordinal))
            return description["NOTE:".Length..].Trim();
        var text = description["NOTE:INSTRUMENT:".Length..];
        var separator = text.IndexOf(':');
        return (separator < 0 ? text : text[(separator + 1)..]).Trim();
    }
}
